python_library(
  name = 'persistence',
  sources = rglobs('*.py'),
  dependencies = [
    'src/python/twitter/common/log',
    'src/python/twitter/common/lang',
    'src/python/twitter/ops/database',
    'src/python/twitter/stressdash/config',
  ]
)
