ENABLE_AUTHENTICATION: true
ELFOWL_AUTH_DOMAIN: .service.smf1.twitter.biz
# created using go/db. 100GB allowance. this should be fine
# for pagerduck use.
MYSQL_HOST: stressdash-staging.rw.ss-001.smf1.db.twitter.biz
MYSQL_DB: stressdash_staging
MYSQL_CRED_PREFIX: rw_db_
TWKEYS: /etc/twkeys/stresstest/stressdash_staging/service.yml
ENABLE_LOGLENS: true
LOGLENS_INDICES: stressdash_staging
